export const ADD_TODO = "ADD_TODO";
export const TODO_TOGGLE_COMPLETION = "TODO_TOGGLE_COMPLETION";
export const TODO_FILTER = "TODO_FILTER";
export const TODO_LIST_TITLE_CHANGE = "TODO_LIST_TITLE_CHANGE";
export const TODO_LIST_DESCRIPTION_CHANGE = "TODO_LIST_DESCRIPTION_CHANGE";